#+title: bisos.bxoGitlab: Python Command-Services for managing GIT repositories of BPO (BISOS Portable Objects) using the gitlab API.
#+DATE: <2024-02-19 Mon 16:27>
#+AUTHOR: Mohsen BANAN
#+OPTIONS: toc:4

Panel Controls:: [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]] [[elisp:(save-buffer)][Save]] [[elisp:(kill-buffer)][Quit]] [[elisp:(bury-buffer)][Bury]]
Links: [[file:./panels/_nodeBase_/fullUsagePanel-en.org]] (Package Panel)

* Overview
bisos.bxoGitlab is a python package that uses the PyCS-Framework for
managing GIT repositories of BPO (BISOS Portable Objects).
bisos.bxoGitlab is layered on top of python-gitlab API.

It is a BISOS-Capability and a Standalone-BISOS-Package.

/bisos.bxoGitlab/ is based on PyCS-Foundation and can be used both as a Command and
as a Service (invoke/perform model of remote operations) using RPYC for central
management of multiple systems.


* Table of Contents     :TOC:
- [[#overview][Overview]]
- [[#about-bisos-----bystar-internet-services-operating-system][About BISOS --- ByStar Internet Services Operating System]]
- [[#bisosbxogitlab-is-a-command-services-pycs-facility][bisos.bxoGitlab is a Command-Services (PyCS) Facility]]
- [[#about-bxogitlabcs][About bxoGitlab.cs]]
- [[#about-python-gitlab-pypi-package-and-python-gitlab-cli][About python-gitlab pypi Package and Python gitlab cli]]
- [[#installation][Installation]]
  - [[#with-pip][With pip]]
  - [[#with-pipx][With pipx]]
- [[#usage][Usage]]
- [[#documentation-and-blee-panels][Documentation and Blee-Panels]]
  - [[#bisosbxogitlab-blee-panels][bisos.bxoGitlab Blee-Panels]]
- [[#support][Support]]

* About BISOS --- ByStar Internet Services Operating System

Layered on top of Debian, *BISOS*: (By* Internet Services Operating System) is a
unified and universal framework for developing both internet services and
software-service continuums that use internet services. See [[https://github.com/bxGenesis/start][Bootstrapping
ByStar, BISOS and Blee]] for information about getting started with BISOS.

bisos.bxoGitlab/ is a small piece of a much bigger picture. *BISOS* is a
foundation for *The Libre-Halaal ByStar Digital Ecosystem* which is described as
a cure for losses of autonomy and privacy that we are experiencing in a book
titled: [[https://github.com/bxplpc/120033][Nature of Polyexistentials]]

* bisos.bxoGitlab is a Command-Services (PyCS) Facility

bisos.bxoGitlab can be used locally on command-line or remotely as a service.
bisos.bxoGitlab is a PyCS multi-unit command-service.
PyCS is a framework that converges developement of CLI and Services.
PyCS is an alternative to FastAPI, Typer and Click.

Within BISOS,  bisos.bxoGitlab is used as a common facility.

bisos.bxoGitlab is a standalone piece of BISOS. It can be used as a self-contained
Python package separate from BISOS. Follow the installtion and usage
instructions below for your own use.

* About bxoGitlab.cs

* About python-gitlab pypi Package and Python gitlab cli

#+begin_src bash
cat ~/.python-gitlab.cfg
gitlab group get --id groupName/subGroup  # id: xxx, name: yyy
gitlab group list --search groupName
gitlab group-project list --group-id tmobile/ranautomation   # Produces only id: not names:
#+end_src


* Installation

The sources for the  bisos.bxoGitlab pip package is maintained at:
https://github.com/bisos-pip/bxoGitlab.

The bisos.bxoGitlab pip package is available at PYPI as
https://pypi.org/project/bisos.bxoGitlab

You can install bisos.bxoGitlab with pip or pipx.

** With pip

If you need access to bisos.bxoGitlab as a python module, you can install it with pip:

#+begin_src bash
pip install bisos.bxoGitlab
#+end_src

** With pipx

If you only need access to bisos.bxoGitlab as a command on command-line, you can install it with pipx:

#+begin_src bash
pipx install bisos.bxoGitlab
#+end_src

The following commands are made available:
- bxoGitlab.cs

* Usage

=bxoGitlab.cs= can be invoked directly as

#+begin_src bash
bin/bxoGitlab.cs
#+end_src

* Documentation and Blee-Panels

Part of ByStar Digital Ecosystem [[http://www.by-star.net]].

This module's primary documentation is in the form of Blee-Panels.
Additional information is also available in: [[http://www.by-star.net/PLPC/180047]]

** bisos.bxoGitlab Blee-Panels

bisos.bxoGitlab Blee-Panles are in ./panels directory.
From within Blee and BISOS these panles are accessible under the
Blee "Panels" menu.

* Support

For support, criticism, comments and questions; please contact the
author/maintainer\\
[[http://mohsen.1.banan.byname.net][Mohsen Banan]] at:
[[http://mohsen.1.banan.byname.net/contact]]


# Local Variables:
# eval: (setq-local toc-org-max-depth 4)
# End:
